# Generated by Django 3.0.7 on 2022-09-03 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppHomeScreenProductBottom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('image', models.ImageField(upload_to='images/')),
                ('details', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('price', models.FloatField(blank=True, default=0, max_length=100, null=True)),
                ('productId', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('offer', models.CharField(blank=True, default='', max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AppHomeScreenProductTop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('image', models.ImageField(upload_to='images/')),
                ('details', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('price', models.FloatField(blank=True, default=0, max_length=100, null=True)),
                ('productId', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('offer', models.CharField(blank=True, default='', max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(default='', max_length=100)),
                ('link', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
