# Generated by Django 4.1.6 on 2023-09-13 19:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AllRooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('room_coustom_id', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('room_welcome_message', models.CharField(blank=True, default='Welcome', max_length=200, null=True)),
                ('room_tag', models.CharField(blank=True, default='Welcome', max_length=200, null=True)),
                ('room_image', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('room_admin_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
