# Generated by Django 4.1.6 on 2023-09-13 20:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='allrooms',
            name='room_admin_profile',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='room_admin_profile', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='allrooms',
            name='room_media_status',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='allrooms',
            name='room_user_can_join',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='allrooms',
            name='room_admin_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_admin_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
