# Generated by Django 4.1.6 on 2023-10-03 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fruitinvestment',
            name='profile_data',
            field=models.CharField(blank=True, default=None, max_length=20000, null=True),
        ),
    ]
