# Generated by Django 4.1.6 on 2023-09-14 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_allrooms_room_admin_profile_isjoinroomsusers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='isjoinroomsusers',
            name='time',
        ),
    ]
