# Generated by Django 4.1.6 on 2023-10-10 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_rename_allmessage_allp2pmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='allp2pmessage',
            name='time',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
