# Generated by Django 4.1.6 on 2023-09-14 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_remove_isjoinroomsusers_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='isjoinroomsusers',
            name='room_join_join_uniq_id',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
