# Generated by Django 4.1.6 on 2023-10-11 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_allp2pmessage_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allrooms',
            name='room_password',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
