# Generated by Django 4.1.6 on 2023-09-14 15:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0005_isjoinroomsusers_room_join_join_uniq_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllSentedGifts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_coustom_unique_id', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('gift_name', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('gift_amount', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('gift_receive_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gift_receive_user', to=settings.AUTH_USER_MODEL)),
                ('gift_sent_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gift_sent_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
