# Generated by Django 4.1.6 on 2023-09-14 22:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0006_allsentedgifts'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllPK',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pk_unique_id', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('pk_time', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('pk_request_receive_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pk_request_receive_user', to=settings.AUTH_USER_MODEL)),
                ('pk_request_sent_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pk_request_sent_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
