# Generated by Django 4.2.6 on 2023-10-26 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_alter_allrooms_room_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allrooms',
            name='room_image',
            field=models.CharField(blank=True, default='https://scontent.fjsr1-1.fna.fbcdn.net/v/t1.15752-9/384546080_253840144277334_7690290843335446763_n.jpg?_nc_cat=105&ccb=1-7&_nc_sid=8cd0a2&_nc_eui2=AeH9N_TFM_IuYw9LHpdVdNLgO50S_JO2B0c7nRL8k7YHR4msuxw4H9cZewENUY-nVcfs0BFwtzCwTCY2vpJ2wZoP&_nc_ohc=gZfCKE6JZfQAX-iQX89&_nc_ht=scontent.fjsr1-1.fna&oh=03_AdSHQkZy6RbxyfRr_aulKoGF51KovdqOUKkiqkYvo0L5Jw&oe=6561E4B7', max_length=200, null=True),
        ),
    ]
