# Generated by Django 4.1.6 on 2023-09-14 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_allpk'),
    ]

    operations = [
        migrations.AddField(
            model_name='allpk',
            name='pk_request_receive_user_balance',
            field=models.CharField(blank=True, default=0, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='allpk',
            name='pk_request_sent_user_balance',
            field=models.CharField(blank=True, default=0, max_length=200, null=True),
        ),
    ]
