# Generated by Django 4.2.6 on 2023-10-26 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_alter_allrooms_room_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='allrooms',
            name='room_sit_10_lock_position',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='allrooms',
            name='room_sit_10_mic_status',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='allrooms',
            name='room_sit_10_password',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='allrooms',
            name='room_sit_9_lock_position',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='allrooms',
            name='room_sit_9_mic_status',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='allrooms',
            name='room_sit_9_password',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
