# Generated by Django 4.2.6 on 2024-01-02 12:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_allrooms_room_sit_10_lock_position_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fruitinvestmenttimeline',
            name='time',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
