# Generated by Django 4.2.6 on 2024-01-03 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0011_fruitinvestmentwinranking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fruitinvestmentwinranking',
            name='win_amount',
            field=models.FloatField(blank=True, default=0.0, max_length=200, null=True),
        ),
    ]
