# Generated by Django 4.1.6 on 2023-09-15 11:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0011_alter_allpk_pk_request_receive_user_profile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='allpk',
            name='pk_end_time',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='allpk',
            name='pk_start_time',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
