# Generated by Django 4.1.6 on 2023-09-15 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0012_allpk_pk_end_time_allpk_pk_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allpk',
            name='pk_end_time',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='allpk',
            name='pk_start_time',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
