# Generated by Django 4.2.6 on 2024-01-03 22:00

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('chat', '0012_alter_fruitinvestmentwinranking_win_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='FruitInvestmentWinLoseRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('win_or_lose_amount', models.FloatField(blank=True, default=0.0, null=True)),
                ('rounds', models.IntegerField(blank=True, default=0, null=True)),
                ('win_fruit_name', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('time', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fruit_investment_record_user_profile', to='authentication.profile')),
            ],
        ),
    ]
