# Generated by Django 4.1.6 on 2023-09-15 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0013_alter_allpk_pk_end_time_alter_allpk_pk_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='allpk',
            name='room_coustom_unique_id',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
