# Generated by Django 4.1.6 on 2023-09-15 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_profile_coin_alter_profile_diamond_and_more'),
        ('chat', '0014_allpk_room_coustom_unique_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='allsentedgifts',
            name='gift_receive_user_profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='gift_receive_user_profile', to='authentication.profile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='allsentedgifts',
            name='gift_sent_user_profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='gift_sent_user_profile', to='authentication.profile'),
            preserve_default=False,
        ),
    ]
