# Generated by Django 4.2.6 on 2024-01-04 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0014_alter_fruitinvestmentwinloserecord_user_profile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fruitinvestmentwinloserecord',
            name='fruit_name',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
