# Generated by Django 4.2.6 on 2024-01-09 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0015_fruitinvestmentwinloserecord_fruit_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fruitinvestmentwinloserecord',
            old_name='win_or_lose_amount',
            new_name='amount',
        ),
        migrations.AddField(
            model_name='fruitinvestmentwinloserecord',
            name='win_amount',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
