# Generated by Django 4.1.6 on 2023-09-17 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0016_allrooms_room_lock_allrooms_room_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allrooms',
            name='room_lock',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
