# Generated by Django 4.2.6 on 2024-01-19 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0016_rename_win_or_lose_amount_fruitinvestmentwinloserecord_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='allrooms',
            name='room_sended_amount',
            field=models.CharField(blank=True, default='0', max_length=200, null=True),
        ),
    ]
