# Generated by Django 4.1.6 on 2023-09-17 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0017_alter_allrooms_room_lock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allrooms',
            name='room_password',
            field=models.CharField(blank=True, default='57706', max_length=200, null=True),
        ),
    ]
