# Generated by Django 4.2.6 on 2024-01-19 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0017_allrooms_room_sended_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='allrooms',
            name='room_theme',
            field=models.CharField(blank=True, default='theme1', max_length=200, null=True),
        ),
    ]
