# Generated by Django 4.1.6 on 2023-09-17 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0018_alter_allrooms_room_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allrooms',
            name='time',
        ),
    ]
