# Generated by Django 4.2.6 on 2024-02-10 20:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0019_allrooms_room_all_joinded_user_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='VIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('price', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('per_day_renewal', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vip_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
