# Generated by Django 4.1.6 on 2023-09-18 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_profile_coin_alter_profile_diamond_and_more'),
        ('chat', '0019_remove_allrooms_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='allrooms',
            name='room_mute_mic_user_profile_banded_list',
            field=models.ManyToManyField(blank=True, related_name='room_mute_mic_user_profile_banded_list', to='authentication.profile'),
        ),
        migrations.AddField(
            model_name='allrooms',
            name='room_mute_mic_user_profile_list',
            field=models.ManyToManyField(blank=True, related_name='room_mute_mic_user_profile_list', to='authentication.profile'),
        ),
    ]
