# Generated by Django 4.2.6 on 2024-02-10 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('chat', '0020_vip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vip',
            name='user',
        ),
        migrations.AddField(
            model_name='vip',
            name='user_profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='vip_user_profile', to='authentication.profile'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vip',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
