# Generated by Django 4.2.6 on 2024-02-19 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0021_remove_vip_user_vip_user_profile_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='allrooms',
            old_name='room_sit_10_mic_status',
            new_name='room_sit_11_mic_status',
        ),
        migrations.AddField(
            model_name='allrooms',
            name='room_sit_12_mic_status',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='allrooms',
            name='room_sit_13_mic_status',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='allrooms',
            name='room_sit_14_mic_status',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='allrooms',
            name='room_sit_15_mic_status',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='allrooms',
            name='room_sit_16_mic_status',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
