# Generated by Django 4.2.6 on 2024-02-19 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0022_rename_room_sit_10_mic_status_allrooms_room_sit_11_mic_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='allrooms',
            name='room_sit_11_lock_position',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='allrooms',
            name='room_sit_11_password',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='allrooms',
            name='room_sit_12_lock_position',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='allrooms',
            name='room_sit_12_password',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='allrooms',
            name='room_sit_13_lock_position',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='allrooms',
            name='room_sit_13_password',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='allrooms',
            name='room_sit_14_lock_position',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='allrooms',
            name='room_sit_14_password',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='allrooms',
            name='room_sit_15_lock_position',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='allrooms',
            name='room_sit_15_password',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='allrooms',
            name='room_sit_16_lock_position',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='allrooms',
            name='room_sit_16_password',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
