# Generated by Django 4.2.6 on 2024-02-23 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0024_allrooms_room_notice_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='allsentedgifts',
            name='time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
