# Generated by Django 4.2.6 on 2024-03-26 15:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_profile_total_receive_coin_and_more'),
        ('chat', '0025_allsentedgifts_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='FruitLoopInvestmentTimeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('end_time', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('time', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FruitLoopInvestmentWinRanking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('win_amount', models.FloatField(blank=True, default=0.0, max_length=200, null=True)),
                ('time', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fruit_loop_investment_amount_user_profile', to='authentication.profile')),
            ],
        ),
        migrations.CreateModel(
            name='FruitLoopInvestmentWinLoseRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(blank=True, default=0.0, null=True)),
                ('win_amount', models.FloatField(blank=True, default=0.0, null=True)),
                ('rounds', models.IntegerField(blank=True, default=0, null=True)),
                ('win_fruit_name', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('fruit_name', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('time', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fruit_loop_investment_win_or_lose_user_profile', to='authentication.profile')),
            ],
        ),
        migrations.CreateModel(
            name='FruitLoopInvestmentRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rounds', models.IntegerField(blank=True, default=0, null=True)),
                ('time', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fruit_loop_investment_record_user_profile', to='authentication.profile')),
            ],
        ),
        migrations.CreateModel(
            name='FruitLoopInvestment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('investment', models.CharField(blank=True, default=None, max_length=20000, null=True)),
                ('profile_data', models.CharField(blank=True, default=None, max_length=20000, null=True)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fruit_loop_investment_user_profile', to='authentication.profile')),
            ],
        ),
    ]
