# Generated by Django 4.2.6 on 2024-06-25 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_profile_total_receive_coin_and_more'),
        ('chat', '0026_fruitloopinvestmenttimeline_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RocketCrashInvestment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('investment_and_profile_data', models.CharField(blank=True, default=None, max_length=20000, null=True)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rocket_crash_investment_user_profile', to='authentication.profile')),
            ],
        ),
    ]
