# Generated by Django 5.1 on 2024-09-08 23:12

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_profile_total_receive_coin_and_more'),
        ('chat', '0027_rocketcrashinvestment'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlotMachineGameInvestment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('investment_and_profile_data', models.CharField(blank=True, default=None, max_length=20000, null=True)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slot_machine_investment_user_profile', to='authentication.profile')),
            ],
        ),
        migrations.CreateModel(
            name='SlotMachineGameInvestmentWinRanking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('win_amount', models.FloatField(blank=True, default=0.0, max_length=200, null=True)),
                ('time', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slot_machine_investment_amount_user_profile', to='authentication.profile')),
            ],
        ),
        migrations.CreateModel(
            name='SlotMachinetGameWinLoseRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(blank=True, default=0.0, null=True)),
                ('win_amount', models.FloatField(blank=True, default=0.0, null=True)),
                ('rounds', models.IntegerField(blank=True, default=0, null=True)),
                ('time', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slot_machine_game_investment_win_or_lose_user_profile', to='authentication.profile')),
            ],
        ),
    ]
