# Generated by Django 5.1 on 2024-09-08 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0028_slotmachinegameinvestment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fruitloopinvestmentwinloserecord',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='fruitloopinvestmentwinloserecord',
            name='fruit_name',
        ),
        migrations.RemoveField(
            model_name='fruitloopinvestmentwinloserecord',
            name='rounds',
        ),
        migrations.RemoveField(
            model_name='fruitloopinvestmentwinloserecord',
            name='time',
        ),
        migrations.RemoveField(
            model_name='fruitloopinvestmentwinloserecord',
            name='win_amount',
        ),
        migrations.RemoveField(
            model_name='fruitloopinvestmentwinloserecord',
            name='win_fruit_name',
        ),
    ]
