# Generated by Django 5.0 on 2024-09-11 15:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0031_multiplespingameinvestmentwinranking_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fruitloopinvestmentwinloserecord',
            name='amount',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='fruitloopinvestmentwinloserecord',
            name='fruit_name',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='fruitloopinvestmentwinloserecord',
            name='rounds',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='fruitloopinvestmentwinloserecord',
            name='time',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='fruitloopinvestmentwinloserecord',
            name='win_amount',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='fruitloopinvestmentwinloserecord',
            name='win_fruit_name',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
