# Generated by Django 5.0 on 2024-09-11 15:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_profile_total_receive_coin_and_more'),
        ('chat', '0032_fruitloopinvestmentwinloserecord_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DragonvsTigerGameInvestmentTimeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('end_time', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('time', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='fruitloopinvestment',
            name='time',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.CreateModel(
            name='DragonvsTigerGameInvestment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('investment', models.CharField(blank=True, default=None, max_length=20000, null=True)),
                ('profile_data', models.CharField(blank=True, default=None, max_length=20000, null=True)),
                ('time', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dragon_vs_tiger_game_investment_user_profile', to='authentication.profile')),
            ],
        ),
        migrations.CreateModel(
            name='DragonvsTigerGameInvestmentRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rounds', models.IntegerField(blank=True, default=0, null=True)),
                ('time', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dragon_vs_tiger_investment_record_user_profile', to='authentication.profile')),
            ],
        ),
        migrations.CreateModel(
            name='DragonvsTigerGameInvestmentWinLoseRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(blank=True, default=0.0, null=True)),
                ('win_amount', models.FloatField(blank=True, default=0.0, null=True)),
                ('rounds', models.IntegerField(blank=True, default=0, null=True)),
                ('win_fruit_name', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('fruit_name', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('time', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dragon_vs_tiger_win_or_lose_user_profile', to='authentication.profile')),
            ],
        ),
        migrations.CreateModel(
            name='DragonvsTigerGameInvestmentWinRanking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('win_amount', models.FloatField(blank=True, default=0.0, max_length=200, null=True)),
                ('time', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dragon_vs_tiger_investment_amount_user_profile', to='authentication.profile')),
            ],
        ),
    ]
