# Generated by Django 5.0 on 2024-09-12 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0034_dragonvstigergamedumyinvestment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dragonvstigergamedumyinvestment',
            old_name='amount',
            new_name='dragon_amount',
        ),
        migrations.AddField(
            model_name='dragonvstigergamedumyinvestment',
            name='tiger_amount',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
