# Generated by Django 4.2.6 on 2024-02-14 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_mvip',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_vip',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
