# Generated by Django 3.0.7 on 2023-01-25 04:09

import authentication.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_unique_id', models.CharField(blank=True, max_length=120)),
                ('image', models.ImageField(null=True, upload_to=authentication.models.get_image_filename, verbose_name='Image')),
            ],
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='division',
            new_name='car_details',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='district',
            new_name='car_model',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='address',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='zip_code',
        ),
        migrations.AddField(
            model_name='user',
            name='is_rider',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='personal_WS_ID',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.CreateModel(
            name='ProfileImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to=authentication.models.get_image_filename, verbose_name='Image')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile_images', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
