# Generated by Django 4.1.6 on 2023-09-14 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='coin',
            field=models.CharField(blank=True, default=0, max_length=400),
        ),
        migrations.AlterField(
            model_name='profile',
            name='diamond',
            field=models.CharField(blank=True, default=0, max_length=400),
        ),
        migrations.AlterField(
            model_name='profile',
            name='total_coin',
            field=models.CharField(blank=True, default=0, max_length=400),
        ),
        migrations.AlterField(
            model_name='profile',
            name='total_diamond',
            field=models.CharField(blank=True, default=0, max_length=400),
        ),
    ]
