# Generated by Django 4.2.6 on 2024-02-27 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_profile_is_mvip_profile_is_vip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='fast_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
