# Generated by Django 4.1.7 on 2023-04-04 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_profile_coin_profile_diamond_profile_totalcoin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='coin',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='diamond',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='totalCoin',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='totalDiamond',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
