# Generated by Django 4.1.7 on 2023-04-04 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_profile_coin_alter_profile_diamond_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='totalCoin',
            new_name='total_coin',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='totalDiamond',
            new_name='total_diamond',
        ),
    ]
