# Generated by Django 4.1.7 on 2023-03-23 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_profile_country_profile_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_email',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
