# Generated by Django 4.2.6 on 2024-03-10 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_profile_fast_name_alter_profile_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='total_receive_coin',
            field=models.CharField(blank=True, default=0, max_length=400),
        ),
        migrations.AddField(
            model_name='profile',
            name='total_receive_diamond',
            field=models.CharField(blank=True, default=0, max_length=400),
        ),
        migrations.AddField(
            model_name='profile',
            name='total_sent_coin',
            field=models.CharField(blank=True, default=0, max_length=400),
        ),
        migrations.AddField(
            model_name='profile',
            name='total_sent_diamond',
            field=models.CharField(blank=True, default=0, max_length=400),
        ),
        migrations.AlterField(
            model_name='profile',
            name='fast_name',
            field=models.CharField(blank=True, default=' ', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_name',
            field=models.CharField(blank=True, default=' ', max_length=50, null=True),
        ),
    ]
