# Generated by Django 4.1.7 on 2023-04-05 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_profile_is_agent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='is_agent',
            new_name='is_host_agent',
        ),
    ]
