# Generated by Django 4.1.7 on 2023-04-07 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_rename_is_agent_profile_is_host_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_recharge_agent',
            field=models.BooleanField(default=False),
        ),
    ]
