# Generated by Django 3.0.7 on 2023-02-03 04:03

import authentication.models
import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_auto_20230203_0400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupimages',
            name='image',
            field=models.ImageField(null=True, upload_to=authentication.models.get_image_filename, verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='profileimages',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
