# Generated by Django 3.0.7 on 2023-02-03 04:10

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_auto_20230203_0403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupimages',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
