# Generated by Django 3.0.7 on 2023-02-03 04:17

import authentication.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_auto_20230203_0415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(null=True, upload_to=authentication.models.get_image_filename, verbose_name='Image'),
        ),
    ]
