# Generated by Django 3.0.7 on 2023-02-03 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0014_auto_20230203_0422'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cover_image',
            field=models.CharField(blank=True, max_length=400),
        ),
    ]
