# Generated by Django 3.0.7 on 2023-02-07 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0015_profile_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='custom_id',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
