# Generated by Django 5.0 on 2024-11-07 13:30

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BannerImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('image', cloudinary.models.CloudinaryField(blank=True, default=None, max_length=255, null=True)),
                ('uploaded', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
