# Generated by Django 4.1.7 on 2023-04-06 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_rename_is_agent_profile_is_host_agent'),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SentGifts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_id', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('gift_name', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('amount', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('receive_user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receive_user_profile', to='authentication.profile')),
                ('sent_user_user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_user_profile', to='authentication.profile')),
            ],
        ),
    ]
