# Generated by Django 5.0 on 2024-11-07 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('product_price', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('product_image', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('uploaded', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
