# Generated by Django 5.0 on 2024-11-07 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_dis',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
