# Generated by Django 4.1.7 on 2023-04-06 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_sentgifts_room_admin_user_user_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sentgifts',
            old_name='room_admin_user_user_profile',
            new_name='room_admin_user_profile',
        ),
    ]
