# Generated by Django 4.1.7 on 2023-03-21 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_bannerimages_alt_bannerimages_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannerimages',
            name='image',
            field=models.CharField(default='', max_length=200),
        ),
    ]
