# Generated by Django 4.1.7 on 2023-04-06 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_rename_room_admin_user_user_profile_sentgifts_room_admin_user_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sentgifts',
            name='room_admin_user_profile',
        ),
    ]
