# Generated by Django 3.0.7 on 2023-01-31 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_auto_20230127_1247'),
        ('home', '0004_p2pmessageuniqueid'),
    ]

    operations = [
        migrations.AddField(
            model_name='p2pmessageuniqueid',
            name='other_user_profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='other_user_profile', to='authentication.Profile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='p2pmessageuniqueid',
            name='user_profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to='authentication.Profile'),
            preserve_default=False,
        ),
    ]
