# Generated by Django 4.1.7 on 2023-04-06 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_rename_is_agent_profile_is_host_agent'),
        ('home', '0005_remove_sentgifts_room_admin_user_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentgifts',
            name='room_admin_user_profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='room_admin_user_profile', to='authentication.profile'),
            preserve_default=False,
        ),
    ]
