# Generated by Django 4.1.7 on 2023-04-06 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_sentgifts_room_admin_user_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentgifts',
            name='receive_user_profile',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='sentgifts',
            name='room_admin_user_profile',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='sentgifts',
            name='sent_user_user_profile',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
