# Generated by Django 3.0.7 on 2023-02-03 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_postimages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postimages',
            name='image',
            field=models.CharField(default='', max_length=500),
        ),
    ]
