# Generated by Django 4.1.7 on 2023-04-06 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_rename_is_agent_profile_is_host_agent'),
        ('home', '0007_alter_sentgifts_receive_user_profile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentgifts',
            name='receive_user_profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='receive_user_profile', to='authentication.profile'),
            preserve_default=False,
        ),
    ]
