# Generated by Django 4.1.7 on 2023-04-06 17:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_rename_is_agent_profile_is_host_agent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0009_alter_sentgifts_receive_user_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyCoinFromAgents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('agent_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_user', to=settings.AUTH_USER_MODEL)),
                ('agent_user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_user_profile', to='authentication.profile')),
                ('buyer_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyer_user', to=settings.AUTH_USER_MODEL)),
                ('buyer_user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyer_user_profile', to='authentication.profile')),
            ],
        ),
    ]
