# Generated by Django 4.1.7 on 2023-04-06 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_buycoinfromagents'),
    ]

    operations = [
        migrations.AddField(
            model_name='buycoinfromagents',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Cancel', 'Cancel')], default='Pending', max_length=10),
        ),
    ]
