# Generated by Django 4.1.7 on 2023-04-06 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_buycoinfromagents_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buycoinfromagents',
            old_name='agent_user_profile',
            new_name='agent_profile',
        ),
        migrations.RenameField(
            model_name='buycoinfromagents',
            old_name='buyer_user_profile',
            new_name='buyer_profile',
        ),
    ]
