# Generated by Django 4.1.7 on 2023-04-06 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_rename_is_agent_profile_is_host_agent'),
        ('home', '0012_rename_agent_user_profile_buycoinfromagents_agent_profile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buycoinfromagents',
            name='agent_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_profile', to='authentication.profile'),
        ),
        migrations.AlterField(
            model_name='buycoinfromagents',
            name='buyer_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyer_profile', to='authentication.profile'),
        ),
    ]
