# Generated by Django 4.1.7 on 2023-04-06 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_rename_is_agent_profile_is_host_agent'),
        ('home', '0013_alter_buycoinfromagents_agent_profile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buycoinfromagents',
            name='agent_profile',
        ),
        migrations.RemoveField(
            model_name='buycoinfromagents',
            name='buyer_profile',
        ),
        migrations.AddField(
            model_name='buycoinfromagents',
            name='agent_user_profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='agent_user_profile', to='authentication.profile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='buycoinfromagents',
            name='buyer_user_profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='buyer_user_profile', to='authentication.profile'),
            preserve_default=False,
        ),
    ]
