# Generated by Django 4.1.7 on 2023-04-06 19:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authentication', '0006_rename_is_agent_profile_is_host_agent'),
        ('home', '0014_remove_buycoinfromagents_agent_profile_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostAgents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Cancel', 'Cancel')], default='Pending', max_length=10)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('agent_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='host_agent_user', to=settings.AUTH_USER_MODEL)),
                ('agent_user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='host_agent_user_profile', to='authentication.profile')),
                ('join_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='host_join_user', to=settings.AUTH_USER_MODEL)),
                ('join_user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='host_join_user_profile', to='authentication.profile')),
            ],
        ),
    ]
