# Generated by Django 4.2 on 2023-04-09 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_hostagents'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentgifts',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
