# Generated by Django 4.2 on 2023-04-09 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_alter_sentgifts_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sentgifts',
            old_name='date',
            new_name='date1',
        ),
    ]
