# Generated by Django 4.2 on 2023-04-09 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_rename_date_sentgifts_date1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentgifts',
            name='date1',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
