# Generated by Django 4.2 on 2023-04-09 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_alter_sentgifts_date1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentgifts',
            name='date1',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
