# Generated by Django 4.2 on 2023-04-09 21:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_alter_sentgifts_date1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentgifts',
            name='date1',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 4, 9, 21, 27, 37, 586958), null=True),
        ),
    ]
