# Generated by Django 4.2 on 2023-04-09 21:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_alter_sentgifts_date1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentgifts',
            name='date1',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
