# Generated by Django 4.2 on 2023-04-09 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_alter_sentgifts_date1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sentgifts',
            old_name='date1',
            new_name='date',
        ),
    ]
