# Generated by Django 4.2 on 2023-04-09 21:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_rename_date1_sentgifts_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sentgifts',
            name='date',
        ),
        migrations.AlterField(
            model_name='sentgifts',
            name='time',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
