# Generated by Django 4.2 on 2023-04-11 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_remove_sentgifts_date_alter_sentgifts_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompetitionTimeLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(default=None, max_length=2)),
                ('day_1', models.CharField(default=None, max_length=2)),
                ('day_2', models.CharField(default=None, max_length=2)),
                ('day_3', models.CharField(default=None, max_length=2)),
                ('day_4', models.CharField(default=None, max_length=2)),
                ('day_5', models.CharField(default=None, max_length=2)),
                ('day_6', models.CharField(default=None, max_length=2)),
                ('day_7', models.CharField(default=None, max_length=2)),
                ('day_8', models.CharField(default=None, max_length=2)),
                ('round_1', models.CharField(default=None, max_length=2)),
                ('round_2', models.CharField(default=None, max_length=2)),
                ('round_3', models.CharField(default=None, max_length=2)),
                ('quarter_final', models.CharField(default=None, max_length=2)),
                ('semi_final', models.CharField(default=None, max_length=2)),
                ('final', models.CharField(default=None, max_length=2)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Off', 'Off')], default='Active', max_length=10)),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
